language: cpp

before_install:
 - sudo add-apt-repository -y "ppa:pasgui/ppa"
 - sudo apt-get -qq update
 - sudo apt-get install premake5

script:
 - premake5 --file=tests/premake5.lua gmake
 - make -C tests/build/gmake release
 - tests/bin/nod_tests